# Generated by Django 6.1.1 on 2026-09-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_statusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('electronic', 'Electronic Repair'), ('mechanical', 'Mechanical Repair')], db_index=True, default='mechanical', help_text='Department handling this repair (Electronic or Mechanical)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('electronic', 'Electronic Repair'), ('mechanical', 'Mechanical Repair')], db_index=True, help_text='Department assigned to technician (Electronic or Mechanical). Owners oversee both.', max_length=20, null=True),
        ),
    ]
